use_frameworks! :linkage => :static

platform :ios, '13.0'

target 'YYVideoListPlayer_Example' do
  pod 'YYVideoListPlayer', :path => '../'

  target 'YYVideoListPlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end


post_install do |installer|
  
  # 1、
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end
  end

  # 2、
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
  end
  post_install do |installer|
    
    # 1、
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
      end
    end

    # 2、
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
    end

    # 3、
    xcconfig_paths = []
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.xcconfigs.each_key do |config_name|
        xcconfig_paths << aggregate_target.xcconfig_path(config_name)
      end
    end
    
    # 4、
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        ref = config.base_configuration_reference
        xcconfig_paths << ref.real_path if ref
      end
    end
    
    # 5、
    xcconfig_paths.compact.each do |path|
      content = File.read(path)
      new_content = content.gsub(
        /^EXCLUDED_ARCHS\[sdk=iphonesimulator\*\]\s*=\s*arm64\s*$/,
        'EXCLUDED_ARCHS[sdk=iphonesimulator*] = '
      )
      File.write(path, new_content) if new_content != content
    end

    # 6、
    patch_private_header_imports(installer)
  end

  def patch_private_header_imports(installer)
    # Xcode 26+ modular builds can reject these legacy header imports.
    private_header_files = [
      'AFNetworking/AFNetworking/AFNetworkReachabilityManager.m',
      'AFNetworking/AFNetworking/AFHTTPSessionManager.m',
      'ZFPlayer/ZFPlayer/Classes/Core/ZFReachabilityManager.m'
    ]

    private_header_files.each do |relative_path|
      source_path = File.join(installer.sandbox.root.to_s, relative_path)
      next unless File.exist?(source_path)

      source = File.read(source_path)
      patched_source = source.gsub(
        /^\s*#import <(?:netinet6\/in6\.h|arpa\/inet\.h)>\s*$\n?/,
        ''
      )
      next if patched_source == source

      begin
        File.chmod(0644, source_path)
      rescue StandardError
      end
      File.write(source_path, patched_source)
    end
  end

  # 3、
  xcconfig_paths = []
  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.xcconfigs.each_key do |config_name|
      xcconfig_paths << aggregate_target.xcconfig_path(config_name)
    end
  end
  
  # 4、
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      ref = config.base_configuration_reference
      xcconfig_paths << ref.real_path if ref
    end
  end
  
  # 5、
  xcconfig_paths.compact.each do |path|
    content = File.read(path)
    new_content = content.gsub(
      /^EXCLUDED_ARCHS\[sdk=iphonesimulator\*\]\s*=\s*arm64\s*$/,
      'EXCLUDED_ARCHS[sdk=iphonesimulator*] = '
    )
    File.write(path, new_content) if new_content != content
  end

  # 6、
  patch_private_header_imports(installer)
end

def patch_private_header_imports(installer)
  # Xcode 26+ modular builds can reject these legacy header imports.
  private_header_files = [
    'AFNetworking/AFNetworking/AFNetworkReachabilityManager.m',
    'AFNetworking/AFNetworking/AFHTTPSessionManager.m',
    'ZFPlayer/ZFPlayer/Classes/Core/ZFReachabilityManager.m'
  ]

  private_header_files.each do |relative_path|
    source_path = File.join(installer.sandbox.root.to_s, relative_path)
    next unless File.exist?(source_path)

    source = File.read(source_path)
    patched_source = source.gsub(
      /^\s*#import <(?:netinet6\/in6\.h|arpa\/inet\.h)>\s*$\n?/,
      ''
    )
    next if patched_source == source

    begin
      File.chmod(0644, source_path)
    rescue StandardError
    end
    File.write(source_path, patched_source)
  end
end
